server:
  port: 10388
  shutdown: graceful

spring:
  application:
    name: coupon-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

eureka:
  client:
    enabled: false

